# Generated by Django 3.0 on 2019-12-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20191207_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mushi',
            old_name='date_posted',
            new_name='date_created',
        ),
    ]
